package problemSolving;

public class FibonacciSeries {
    /*
     *Java program to create fibonacci series using recursion and for loop
     * The fibonacci number is generated by adding the previous two numbers - F(N) = F(N-1) + F(N-2)
     * @autor Pabel Lopez
     * */
    public static void main(String[] args) {
        System.out.println(getNumberSeries(20));
        printFibonacciSeries(20);
    }

    public static int getNumberSeries(int number){
        //this will be only returning the last number of the series
        //base scenario, when number is one
        if (number <=1){
            return number;
        }
        //recursion, the method get self-called until reach base scenario
        return getNumberSeries(number -1) + getNumberSeries(number -2);
    }

    public static void printFibonacciSeries(int count) {
        //base scenario 0, 1, 1, 2, 3, 5, 8, 13, 21...
        int a = 0;
        int b = 1;
        int c = 1;
        for (int i = 1; i <= count; i++) {
            System.out.print(a + ", ");
            a = b;
            b = c;
            c = a + b;
        }
        System.out.print(a);
    }
}
